#!/bin/sh

"${AWK=awk}" '
BEGIN {
    n = 7
    pi = 3.141592653589793

    rlo = 0
    rhi = 1
    dr = (rhi - rlo)/n
    plo = 0
    phi = 2*pi
    a = 4
    k = 0
    for (i = 0; i < n; i++) {
	m = a*(2*i + 1)
	for (j = 0; j < m; j++) {
	    dp = (phi - plo)/m
	    r = rlo + dr * (i + 1/2)
	    p = plo + dp * (j + 1/2)
	    x[k] = r*cos(p)
	    y[k] = r*sin(p)
	    ksi[k] = vorticity(x[k], y[k])
	    k++
	}
    }
    m = k
    dA = pi^2/m
    for (k = 0; k < m; k++)
	printf "%.16e %.16e %.16e\n", x[k], y[k], ksi[k] * dA
}

function vorticity(x, y,   inside)
{
    r2 = x^2 + y^2
    inside = r2 < 1
    return inside ? (1 - r2)^3 : 0
}

'
