#!/bin/sh

"${AWK=awk}" '
BEGIN {
    n = 7
    pi = 3.141592653589793
    ksi = 1

    alo = 0
    ahi = 1
    da = (ahi - alo)/n

    blo = 0
    bhi = 2
    db = (bhi - blo)/n

    plo = 0
    phi = 2*pi

    k = 4
    for (i = 0; i < n; i++) {
	m = k*(2*i + 1)
	for (j = 0; j < m; j++) {
	    dp = (phi - plo)/m
	    a = alo + da * (i + 1/2)
	    b = blo + db * (i + 1/2)
	    p = plo + dp * (j + 1/2)
	    x = a*cos(p)
	    y = b*sin(p)
	    printf "%.16e %.16e %.16e\n", x, y, ksi
	}
    }
}
'
