#!/bin/sh

"${AWK=awk}" '
BEGIN {
    n = 14
    pi = 3.141592653589793
    a = 1
    b = 2
    ksi = 1

    rlo = 0
    rhi = 2
    dr = (rhi - rlo)/n
    plo = 0
    phi = 2*pi
    c = 4
    k = 0
    for (i = 0; i < n; i++) {
	m = c*(2*i + 1)
	for (j = 0; j < m; j++) {
	    dp = (phi - plo)/m
	    r = rlo + dr * (i + 1/2)
	    p = plo + dp * (j + 1/2)
	    u = r*cos(p)
	    v = r*sin(p)
	    if (ellipse(u, v)) {
		x[k] = u
		y[k] = v
		k++
	    }
	}
    }
    m = k

    A = pi * a * b
    dA = A / m
    for (k = 0; k < m; k++)
	printf "%.16e %.16e %.16e\n", x[k], y[k], ksi * dA

}

function ellipse(x, y)
{
    return x^2/a^2 + y^2/b^2 < 1
}

'
