load("vect");
express([dx, dy, 0] ~ [0, 0, 1]);

assume(y > 0);
factor(2 * %pi * integrate(exp(-z^2/d^2), z, 0, y));

J2(z):=bessel_j(2, z);

f(y):= 1 / (3 * %pi * y^2) * (4 * J2(2*y) - J2(y));
G(dr):=1/d^2 * f(dr/d);
define(g(y), 2*%pi*integrate(f(y)*y, y, 0, y));
G(dr);
g(dr/d), expand;

g(y);

define(f0(y), expand(taylor(f(y)*y, y, 0, 3)));
draw2d(explicit(f(y) * y, y, 0, 10), 'color = red, explicit(f0(y), y, 0, 0.05));